steps:
  - name: gcr.io/cloud-builders/docker
    id: planner-cache
    args: ['pull', '${_PLANNER_CACHE_IMAGE}']
    allowFailure: true
  - name: gcr.io/cloud-builders/docker
    id: control-cache
    waitFor: ['-']
    args: ['pull', '${_CONTROL_CACHE_IMAGE}']
    allowFailure: true
  - name: gcr.io/cloud-builders/docker
    id: web-cache
    waitFor: ['-']
    args: ['pull', '${_WEB_CACHE_IMAGE}']
    allowFailure: true
  - name: gcr.io/cloud-builders/docker
    id: planner
    waitFor: ['planner-cache']
    args: ['build', '--cache-from', '${_PLANNER_CACHE_IMAGE}', '-t', '${_PLANNER_IMAGE}', '-f', 'Dockerfile.planner', '.']
  - name: gcr.io/cloud-builders/docker
    id: control
    waitFor: ['control-cache']
    args: ['build', '--cache-from', '${_CONTROL_CACHE_IMAGE}', '-t', '${_CONTROL_IMAGE}', '-f', 'Dockerfile.control', '.']
  - name: gcr.io/cloud-builders/docker
    id: web
    waitFor: ['web-cache']
    args: ['build', '--cache-from', '${_WEB_CACHE_IMAGE}', '-t', '${_WEB_IMAGE}', '-f', 'Dockerfile.web', '.']
images: ['${_PLANNER_IMAGE}', '${_CONTROL_IMAGE}', '${_WEB_IMAGE}']
timeout: 1200s
