steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - pull
      - ${_RUNNER_IMAGE}
    allowFailure: true
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --cache-from
      - ${_RUNNER_IMAGE}
      - -t
      - ${_RUNNER_IMAGE}
      - -f
      - Dockerfile
      - .
images:
  - ${_RUNNER_IMAGE}
